import { CORGIS,CORGI_BONE_PRICE,gameState,type CorgiId } from './GameState';
import { storage,STORAGE_KEYS as K } from './Storage';
import { PREMIUM_EXPANSION } from './PremiumExpansionCatalog';
import { buildPremiumPortrait,buildPremiumRun } from './PremiumExpansionArt';
let installed=false;
function registerDefinitions():void{for(const def of PREMIUM_EXPANSION){if(CORGIS.some(c=>String(c.id)===def.id))continue;const id=def.id as CorgiId;CORGIS.push({id,name:def.name,texture:`corgi_${def.id}`,runSheetKey:`${def.id}_run`,runAnimKey:`${def.id}_run`,jumpFrame:2,fallFrame:6,landFrame:0,premium:true,entitlementProducts:['com.corgihop.all_corgis']});(CORGI_BONE_PRICE as Record<string,number>)[def.id]=def.price;if(!(def.id in(gameState.boneUnlocks as Record<string,boolean>)))(gameState.boneUnlocks as Record<string,boolean>)[def.id]=false;}const classic=CORGIS.find(c=>c.id==='classic');if(classic){classic.runSheetKey='classic_natural_run';classic.runAnimKey='classic_natural_run';classic.jumpFrame=2;classic.fallFrame=6;classic.landFrame=0;}}
function restoreExpansionSaves():void{const ids=new Set(PREMIUM_EXPANSION.map(d=>d.id));const originalLoad=gameState.load.bind(gameState);gameState.load=()=>{const selected=storage.getString(K.selectedCorgi,'classic');const unlocks=storage.getJSON<Record<string,boolean>>(K.boneUnlocks,{});originalLoad();for(const def of PREMIUM_EXPANSION)(gameState.boneUnlocks as Record<string,boolean>)[def.id]=!!unlocks[def.id];if(ids.has(selected))gameState.selectedCorgi=selected as CorgiId;};}
function installTextureBuilder(C:{prototype:object}):void{const p=C.prototype as any,o=p.create;p.create=function(...args:unknown[]){for(const d of PREMIUM_EXPANSION){buildPremiumPortrait(this,d);buildPremiumRun(this,d,`${d.id}_run`);}buildPremiumRun(this,null,'classic_natural_run');return o.apply(this,args);};}
export function installPremiumExpansion(C:{prototype:object}):void{if(installed)return;installed=true;registerDefinitions();restoreExpansionSaves();installTextureBuilder(C);}
